title: Enrile Fortioh Zah
logo: Enrile.png
description: A Data Analyst with about 2 years Experience in Report Automation Using Advanced Excel, Data Manipulation and Interogation on SQL and Business Interlligence Report on Power BI.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
